/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/**
 * Dummy code
 */
public class Library {
    /**
     * Dummy method
     * 
     * @return value
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
